In [1]:
import numpy as np
import DualNumber as d

# Scalar function, scalar input, returns scalar

In [2]:
def f(x):
    return x**3

p = 5  # evaluation point
p_x = d.Dual(p) # call Dual object

# should print f(p) + e df/dx evaluated at p
f(p_x)

125.00 + e 75.00

In [3]:
# Check
def df_dx(x):
    return 3*x**2

print(f(p), df_dx(p))

125 75


# Scalar function, vector input, returns gradient vector

In [4]:
def f(x, y): # can be x, y, x_0, x_1, whatev
    return 3*x*y - 2*y**3/x

p = np.array([5, 2]) # evaluation point (x, y) = (5, 3)

p_x = d.Dual(p[0], idx=0, x=p) 
p_y = d.Dual(p[1], idx=1, x=p)

# should print f(p), grad(f) evaluated at p
f(p_x, p_y)

26.80 + e [ 6.64 10.2 ]

In [5]:
# Check
def grad_f(x, y):
    return (3*y + 2*y**3/x**2, 3*x - 6*y**2/x)

print(f(*p), grad_f(*p))

26.8 (6.64, 10.2)


# Vector function, vector input, returns Jacobian matrix

In [6]:
def F(x, y):
    f1 = x**2 + x*y + 2
    f2 = x*y**3 + x**2
    f3 = y**3/x + x + x**2*y**2 + y**4
    return np.array([f1, f2, f3])

p = np.array([1, 2])
p_x = d.Dual(p[0], idx=0, x=p)
p_y = d.Dual(p[1], idx=1, x=p)

F(p_x, p_y)

array([5.00 + e [4. 1.], 9.00 + e [10. 12.], 29.00 + e [ 1. 48.]],
      dtype=object)

Kind of ugly, but for each $i$th entry, the real part is the $i$th component of $\mathbf{F}(\mathbf{p})$ and the dual part is the corresponding row in our Jacobian! The output can be cleaned up a bit with

In [7]:
ad = F(p_x, p_y)

Jac = np.empty((F(*p).size, p.size))
for i, f in enumerate(ad):
    Jac[i] = f.d

Jac

array([[ 4.,  1.],
       [10., 12.],
       [ 1., 48.]])

where the output is automatically an `ndarray`

In [8]:
# Check
def jac_F(x, y):
    grad_f1 = np.array([2*x + y, x])
    grad_f2 = np.array([y**3 + 2*x, 3*x*y**2])
    grad_f3 = np.array([-y**3/x**2 + 1 + 2*x*y**2, 
                        3*y**2/x + 2*x**2*y + 4*y**3])
    return(np.array([grad_f1, grad_f2, grad_f3]))

print(F(*p))
print()
print(jac_F(*p))

[ 5.  9. 29.]

[[ 4.  1.]
 [10. 12.]
 [ 1. 48.]]


# Doctest

In [9]:
import doctest
doctest.testmod(d, verbose=True)

Trying:
    z = Dual(1, 2) + Dual(3, 4)
Expecting nothing
ok
Trying:
    print(z)
Expecting:
    4.00 + e 6.00
ok
Trying:
    z = 2 + Dual(1, 2)
Expecting nothing
ok
Trying:
    print(z)
Expecting:
    3.00 + e 2.00
ok
Trying:
    z = Dual(1, 2) * Dual(3, 4)
Expecting nothing
ok
Trying:
    print(z)
Expecting:
    3.00 + e 10.00
ok
Trying:
    z = 2 * Dual(1, 2)
Expecting nothing
ok
Trying:
    print(z)
Expecting:
    2.00 + e 4.00
ok
Trying:
    z = Dual(1, 2)
Expecting nothing
ok
Trying:
    print(-z)
Expecting:
    -1.00 - e 2.00
ok
Trying:
    z = Dual(1, 2)
Expecting nothing
ok
Trying:
    print(+z)
Expecting:
    1.00 + e 2.00
ok
Trying:
    z = Dual(1, 2) ** Dual(3, 4)
Expecting nothing
ok
Trying:
    print(z)
Expecting:
    1.00 + e 6.00
ok
Trying:
    z = Dual(1, 2)
Expecting nothing
ok
Trying:
    print(z)
Expecting:
    1.00 + e 2.00
ok
Trying:
    z = 2 - Dual(1, 2)
Expecting nothing
ok
Trying:
    print(z)
Expecting:
    1.00 - e 2.00
ok
Trying:
    z = 2 / Dual(1, 2)
Expe

TestResults(failed=0, attempted=34)